### ISSUE TITLE
Cant connect to Blynk Cloud server via  4GEE mobile hotspot device

### ISSUE THREAD

**Issue by Johnep101** [blynkkk/docs#22]
Hi,
I have a 3 phase power measurement unit I built to check out my power usage before installing solar panels.
it uses a Wemos D1 R2 mini connected to the Blynk Cloud server and has been working perfectly for months.
I am trying to use the unit to monitor a local Museums power usage, they don't have WiFi so I thought I could use my mobile 4GEE hot spot device but unfortunately, although the D1 connects to the hot spot (I can see it connected to the internet on the hot spot status page) and via the serial monitor, but for some reason it won't connect to the Blynk server. I can't see any settings in the hot spot that would stop communications. With my iPad connected via the hot spot I can see all my other Blynk units (connected through my standard router)all working properly.
The hot spot allows access for my iPad to the internet without issue, ( using nPerf speed test I get 6.7 MbpS download, 13.5Mbps upload and avg latency of 137mS)
Any ideas please?
Thanks!
John 
Diagnostics .....................
serial output if I change ssid and password to main router ( and unit works ok):-
⸮Hl⸮⸮⸮l$⸮p :I⸮⸮ connecting to wifi
 wifi connected
 connecting to blynk
 Blynk connected

serial output if I change ssid and password to 4G mobile hotspot :-
⸮Hl⸮⸮⸮ld⸮p :I⸮⸮ connecting to wifi
 wifi connected
 connecting to blynk. ......   and then nothing else and unit not working

Code snippet ............... (the same for both cases only SSID and password are changed)
              WiFi.mode(WIFI_STA); 
              Serial.println(" connecting to wifi");           
              WiFi.begin(ssid, password);            
              while (WiFi.waitForConnectResult() != WL_CONNECTED) {
                WiFi.begin(ssid, password);            
               }
               Serial.println(" wifi connected");
              ArduinoOTA.setHostname(host);
              ArduinoOTA.onError([](ota_error_t error) {
                (void)error;
                ESP.restart();
              });
            
              /* setup the OTA server */
              ArduinoOTA.begin();
            
  //Blynk setup ...............................
              
     Serial.println(" connecting to blynk");
     Blynk.begin(auth, ssid, password); 
     Serial.println(" Blynk connected");

**Comment by Johnep101** [comment]
UPDATE, just checked using the mobile hotspot on my iPhone, guess what, it works! but I can't leave my phone at the museum!

**Comment by doom369** [comment]
Please use https://community.blynk.cc/ for questions like this. From your description seems like something android specific.
