### ISSUE TITLE
Troubleshooting

### ISSUE THREAD

**Issue by Mark-Pan** [blynkkk/docs#46]
https://app.gitbook.com/@blynk-iot/s/en/troubleshooting/untitled/@drafts

Troublesootng should have structure:
- Error/Trouble
Possible Solutions

none of the issues is covered like that

For example:
- Can’t log in
What could be the reason
What’s the solution

- Don’t receieve email
What could be the possible reason
Solution

The problem should be clearly stated

**Comment by Mark-Pan** [comment]
List of possible issues:
- Can’t log in //mind GeoDNS
- Don’t receieve email
- No connection to server pop-up
- My API request doesn't work //Invalid Token, 
- I can't erase data from a device //there's a delay
- I can't see all metadata in Blynk.App //not all metadata can be viewed now, will enhance in future
- I can't see enumerable datastreams in Blynk.App //not supported by every widget at the moment, will enhance in future
- Device lost it's connection //wi-fi network password could be changed (reprovision then), other connectivity issues
- I can't add logo of my organization
- I can't add an image to Blynk.App widget
- Changes made to Device Template (all tabs) are not applied //forgot to click save or clicked during server disconnect
- Not correct device during add device
- I press Blynk.App button and nothing happens to the device //connectivity or device issues; mind that Blynk is a cloud platform, there's no offline support for now but will be enhanced one day
- No devices in Automation
- No enumerable datastreams in Automations //not implemented yet, will be done in the future
- I've created dashboard in web and don't see it in mobile app (or reverse)

**Comment by Agnetka-qa** [comment]
- **Can’t log in** 

**What could be the reason**
-wrong email address
-the password is incorrect
-the user with the specified email address is not registered in the system
**What’s the solution**
-specify correct email address
-reset password
-register with a different email address


- **Don’t receieve email**

**What could be the reason**
-you entered an incorrect email address
-the letter got into the spam folder
**What’s the solution**
-specify correct email address
-check your spam folder

- **No connection to server pop-up**

**What could be the reason**
-you do not have an internet connection
-the server is rebooting

**What’s the solution**
-connect to the internet
-you should wait for a while to reboot the server

- **My API request doesn't work //Invalid Token**

**What could be the reason**
-the device token is specified incorrectly
**What’s the solution**
-check the device token in the Device Info tab

**Comment by Mark-Pan** [comment]
My app originally worked but now it will not load at all. It won’t connect to the server at all.
I then created an account under a different email address and it worked fine.

geo DNS issue, he need to wait for the iOS app to be released and fixed. Eugene should provide ETA
