### ISSUE TITLE
Pull Request basic.

### ISSUE THREAD

**Issue by DmytroTool** [blynkkk/docs#49]
First i crate a file/branch, fill it with datas and then making pull request comparing with existing branch? 
<img width="1269" alt="Screenshot 2021-06-08 at 19 07 21" src="https://user-images.githubusercontent.com/84926027/121220056-f5380d00-c88c-11eb-9b11-e6a0be5694bd.png">

**Comment by Mark-Pan** [comment]
https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by DmytroTool** [comment]
@Mark-Pan 
<img width="1279" alt="Screenshot 2021-06-09 at 10 28 45" src="https://user-images.githubusercontent.com/84926027/121311911-8949b900-c90d-11eb-9c56-19735649ac01.png"> Can't understand why there is very few files to change.
