### ISSUE TITLE
rename Products -> Templates

### ISSUE THREAD

**Issue by Mark-Pan** [blynkkk/docs#51]
find and replace everywhere it is

**Comment by doom369** [comment]
@Mark-Pan it's a 5-minute task. Why do you create a ticket? Just go and fix it.

Fixed by myself.

**Comment by Mark-Pan** [comment]
@doom369 because of there are screenshots with `Product`
Or leave it to Design team?

**Comment by doom369** [comment]
@Mark-Pan create separate ticket for the design team.
