### ISSUE TITLE
different screens in the documentation and in the app

### ISSUE THREAD

**Issue by Agnetka-qa** [blynkkk/docs#54]
AR docs: 
![image](https://user-images.githubusercontent.com/65705128/121896768-5434d080-cd2a-11eb-9431-0f4be1cb93fc.png)

AR Android:
![image](https://user-images.githubusercontent.com/65705128/121896959-8d6d4080-cd2a-11eb-87d0-92e6256c2849.png)

AR iOS: 
![image](https://user-images.githubusercontent.com/65705128/121897124-b55ca400-cd2a-11eb-885b-2d82204f6c5b.png)

**Comment by vveretko** [comment]
It's the same as in the iOS app
