### ISSUE TITLE
Create .csv file with metadata

### ISSUE THREAD

**Issue by Mark-Pan** [blynkkk/docs#61]
@doom369 @EarlOld confirm this guide's text is fine or comment what's wrong and how it should be please

create a text file with the use of your text editor
type metafields names separated with comas in the first row
type metafields contents keeping the same order and separating them with comas in below rows
repeat previous step as much as how many tokens you're going to create
be sure to leave the cursor at the end of the last metadata row, otherwise the file won't be accepted
save the file giving it .csv format
or
create a table using office package software (such as MS Excel, OpenOffice Calc, else)
type metafields names in separate columns in the first row
type metafields contents in the corresponding columns of the below rows
repeat previous step as much as how many tokens you're going to create
save it as .csv file
if your file is not accepted, edit it with your text editor by placing the cursor at the end of the last metadata row. Save it.

**Comment by Mark-Pan** [comment]
https://github.com/blynkkk/dash/issues/15893

**Comment by doom369** [comment]
Who needs all this text? Just provide a simple example and that's it.
